"""add user first and last name, create an address class for inhabitatns addrees details

Revision ID: 2612e3dd3837
Revises: 7f3384cf18d0
Create Date: 2026-08-08 09:18:40.792890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2612e3dd3837'
down_revision: Union[str, Sequence[str], None] = '7f3384cf18d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addressdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quater', sa.String(length=100), nullable=False),
    sa.Column('street_address', sa.String(length=100), nullable=True),
    sa.Column('Nearest_landmark', sa.String(length=100), nullable=True),
    sa.Column('inhabitant_id', sa.Integer(), nullable=False),
    sa.Column('image_file', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['inhabitant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('firstname', sa.String(length=100), server_default='unknown', nullable=False))
    op.add_column('users', sa.Column('lastname', sa.String(length=100), server_default='unknown', nullable=False))
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    op.drop_table('addressdata')
    # ### end Alembic commands ###
