"""added role and correct spelling address model

Revision ID: 263c1ae202d2
Revises: 2612e3dd3837
Create Date: 2026-08-09 15:31:08.133863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '263c1ae202d2'
down_revision: Union[str, Sequence[str], None] = '2612e3dd3837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addressdata', sa.Column('nearest_landmark', sa.String(length=100), nullable=True))
    op.drop_column('addressdata', 'Nearest_landmark')
    user_role = sa.Enum('REGULAR', 'ADMIN', 'SUPER_USER', 'MEGA_USER', name='userrole')
    user_role.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', user_role, server_default='REGULAR', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    sa.Enum(name='userrole').drop(op.get_bind(), checkfirst=True)
    op.add_column('addressdata', sa.Column('Nearest_landmark', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('addressdata', 'nearest_landmark')
    # ### end Alembic commands ###
