"""added explicitforeingkeys for user relations to different models.

Revision ID: 515a40d77908
Revises: c0f3d7a5201d
Create Date: 2026-08-14 14:50:36.956474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515a40d77908'
down_revision: Union[str, Sequence[str], None] = 'c0f3d7a5201d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'profiles', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='unique')
    # ### end Alembic commands ###
