"""add pickup status column

Revision ID: 8fefb9d07f7b
Revises: df34a03ebfb4
Create Date: 2026-08-12 03:42:10.527207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fefb9d07f7b'
down_revision: Union[str, Sequence[str], None] = 'df34a03ebfb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickups', sa.Column('courier_id', sa.Integer(), nullable=True))
    op.add_column('pickups', sa.Column('status', sa.Integer(), server_default='1', nullable=False))
    op.add_column('pickups', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('pickups', sa.Column('pickup_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'pickups', ['pickup_id'])
    op.create_foreign_key(None, 'pickups', 'users', ['courier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pickups', type_='foreignkey')
    op.drop_constraint(None, 'pickups', type_='unique')
    op.drop_column('pickups', 'pickup_id')
    op.drop_column('pickups', 'created_at')
    op.drop_column('pickups', 'status')
    op.drop_column('pickups', 'courier_id')
    # ### end Alembic commands ###
