"""add waste categories wastes and pickups

Revision ID: df34a03ebfb4
Revises: 263c1ae202d2
Create Date: 2026-08-09 17:24:53.970655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'df34a03ebfb4'
down_revision: Union[str, Sequence[str], None] = '263c1ae202d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    waste_category_name = postgresql.ENUM(
        'BIODEGRADABLE', 'NON_BIODEGRADABLE', 'MIXED',
        name='wastecategoryname'
    )
    pickup_time_slot = postgresql.ENUM(
        'MORNING', 'MIDDAY', 'EVENING',
        name='pickuptimeslot'
    )
    waste_category_name.create(op.get_bind(), checkfirst=True)
    pickup_time_slot.create(op.get_bind(), checkfirst=True)
    op.create_table('waste_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', postgresql.ENUM('BIODEGRADABLE', 'NON_BIODEGRADABLE', 'MIXED', name='wastecategoryname', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wastes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('producer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['waste_categories.id'], ),
    sa.ForeignKeyConstraint(['producer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pickups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waste_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('pickup_date', sa.Date(), nullable=False),
    sa.Column('time_slot', postgresql.ENUM('MORNING', 'MIDDAY', 'EVENING', name='pickuptimeslot', create_type=False), nullable=False),
    sa.Column('image_file', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['waste_id'], ['wastes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    categories = sa.table(
        'waste_categories',
        sa.column('name', postgresql.ENUM(name='wastecategoryname', create_type=False)),
    )
    op.bulk_insert(categories, [
        {'name': 'BIODEGRADABLE'},
        {'name': 'NON_BIODEGRADABLE'},
        {'name': 'MIXED'},
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pickups')
    op.drop_table('wastes')
    op.drop_table('waste_categories')
    sa.Enum(name='pickuptimeslot').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='wastecategoryname').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
